version: "3.9"

services:
  ktor-server:
    build: .
    ports:
      - "80:80"
    links:
      - "db:db"
  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: tiagonuneslx
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db
  admin:
    image: adminer
    ports:
      - "8080:8080"